default: &default
  adapter: postgresql
  encoding: unicode
  username: hirumi
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_world_development

test:
  <<: *default
  database: hello_world_test

production:
  <<: *default
  database: hello_world_production
  username: hello_world
  password: <%= ENV["HELLO_WORLD_DATABASE_PASSWORD"] %>
